### ISSUE TITLE
Feature suggestion / what do I change...

### ISSUE THREAD

**Issue by steveharman** [moomerman/Sounds#4]
It would be great if opening Sounds defaulted to the station list instead of 6 Music.  

Nothing against 6, although it isn't what it was, but perhaps opening to this might be an idea?  Alternatively - is there somewhere I can edit to specify the URL locally?

Thanks

<img width="1227" alt="Screenshot 2021-03-17 at 13 54 26" src="https://user-images.githubusercontent.com/12557929/111479685-1a532e80-8729-11eb-8beb-67e689ceb9f4.png">

**Comment by steveharman** [comment]
Actually, I did a search on bbc.co.uk in the code and changed it.  

As an unrelated idea; is there any way to implement a "Quit" control?  There doesn't seem to be any way of stopping Sounds except via Activity Monitor.

Thanks

**Comment by gmclean** [comment]
You can quit using Command+Q as long as the Sounds app has foc us.

**Comment by steveharman** [comment]
Ah, right you are.  I was looking for a menu-item, but Cmd-Q works perfectly.  Thanks

**Comment by moomerman** [comment]
Latest version defaults to station list and has a right-click menu bar with a Quit action 🚀
